# Generated by Django 4.1 on 2022-08-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signinapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
