# Generated by Django 4.1 on 2022-08-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signinapi', '0004_test_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
